dir:
  base_dir: ./model

train:
  batch_size: 64
  learning_rate: 0.001
  epochs: 100
  loss_fn: masked MAELoss
  optimizer: Adam
  weight_decay: 0.01

model:
  model_name: FNN

data:
  data_dir: /Users/panwang/Datasets/METR-LA/metr-la.h5
  adj_mx_dir: /Users/panwang/Datasets/METR-LA/adj_mx_la.pkl
  train_ratio: 0.8
  test_ratio: 0.1
  val_ratio: 0.1
  seq_len: 12
  horizon: 12


